apiVersion: v1
kind: Service
meta
  name: stockseva-service
spec:
  selector:
    app: stockseva
  ports:
  - name: http
    port: 80              # External port
    targetPort: 8501      # Container port (Streamlit)
    protocol: TCP
  type: ClusterIP         # Use LoadBalancer/NodePort for external access