# sonar-project.properties
sonar.projectKey=stockseva-streamlit
sonar.projectName=StockSeva Streamlit App
sonar.sources=.
sonar.python.version=3.10
sonar.inclusions=**/*.py
sonar.exclusions=**/tests/**,**/__pycache__/**,**/*.pyc
sonar.sourceEncoding=UTF-8